backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "public/images/uploads" # Media files will be stored in the repo under public/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "blog/posts/{{slug}}"
    view_filters:
      - label: "Draft posts"
        field: "draft"
        pattern: "true"
    view_groups:
      - label: "Year"
        field: "date"
        pattern: 'YYYY'
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "../../../layouts/MarkdownPostLayout.astro"
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: true
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Publish Date"
        name: "pubDate"
        widget: "datetime"
      - label: "Featured Image"
        name: "featuredImage"
        widget: "image"
      - label: "Description"
        name: "description"
        widget: "text"
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: []
      - label: "Body"
        name: "body"
        widget: "markdown"
